version: '3.8'

services:
  postgres:
    container_name: course-platform-db
    image: postgres
    ports:
      - 5432:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres